{
 "cells": [
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-04-21T10:09:36.824370Z",
     "start_time": "2025-04-21T10:05:43.468488Z"
    }
   },
   "cell_type": "code",
   "source": [
    "import time\n",
    "number = int(input(\"Hello Adventurer! When you're ready to begin just type in a 1\"))\n",
    "if number == 1:\n",
    "    print(\"\"\"\n",
    " _____                    _\n",
    "|_   _|__ _ __ ___  _ __ | | ___\n",
    "  | |/ _ \\\\ '_ ` _ \\\\| '_ \\\\| |/ _ \\\\\n",
    "  | |  __/ | | | | | |_) | |  __/\n",
    "  |_|\\\\___|_|_|_| |_| .__/|_|\\\\___|\n",
    "   / \\\\   __| |_   _|_|_ _ __ | |_ _   _ _ __ ___\n",
    "  / _ \\\\ / _` \\\\ \\\\ / / _ \\\\ '_ \\\\| __| | | | '__/ _ \\\\\n",
    " / ___ \\\\ (_| |\\\\ V /  __/ | | | |_| |_| | | |  __/\n",
    "/_/   \\\\_\\\\__,_| \\\\_/ \\\\___|_| |_|\\\\__|\\\\__,_|_|  \\\\___|\n",
    "\"\"\")\n",
    "\n",
    "    time.sleep(1)\n",
    "    print(\"\\\"Welcome to the Minigame!\\\"\")\n",
    "    time.sleep(1)\n",
    "    print(\"\\n\\\"This is not gonna be some cliche adventure. It'll be unique for sure!\\\"\")\n",
    "    time.sleep(3)\n",
    "    print(\"\\n\\\"So let me think of something...\\\"\")\n",
    "    time.sleep(8)\n",
    "    print(\"\\n\\\"Wait a second my god!\\\"\")\n",
    "    time.sleep(3)\n",
    "    print(\"\\n\\\"You're probably one of these TikTok kiddies. I can tell from you're attention span.\\\"\")\n",
    "    time.sleep(4)\n",
    "    print(\"\\n\\\"Wait! I almost got it...\\\"\")\n",
    "    time.sleep(6)\n",
    "    print(\"\\n\\\"Oh haha, yeah I know a great, non cliche start to this adventure!\\\"\")\n",
    "    time.sleep(2)\n",
    "    print(\"\\n\\\"Here we go!\\\"\")\n",
    "    print(\"\\n\")\n",
    "\n",
    "    # Now the first scene starts\n",
    "    time.sleep(3)\n",
    "    print(\"\"\"\n",
    "You awaken in a dark forest. The trees whisper in the wind.\n",
    "Two paths lie before you...\n",
    "\"\"\")\n",
    "    time.sleep(5)\n",
    "    print(\"\"\"\n",
    "        ||      ||\n",
    "        ||      ||\n",
    "     ___||______||_____\n",
    "    /    1     2      /\n",
    "   /                 /\n",
    "  /                 /\n",
    " /                 /\n",
    "/_________________/\n",
    "\"\"\")\n",
    "    time.sleep(1)\n",
    "\n",
    "    choice = input(\"Do you take path 1 (left) or path 2 (right)? Type 1 or 2: \")\n",
    "\n",
    "    if choice == \"1\":\n",
    "        print(\"\\nYou walk down the left path and hear the howling of wolves...\")\n",
    "        # that's choice number 1\n",
    "    elif choice == \"2\":\n",
    "        print(\"\\nYou follow the right path and see the glow of a mysterious light...\")\n",
    "        # this is number 2\n",
    "    else:\n",
    "        print(\"You must choose 1 or 2 to proceed on your adventure!\")\n",
    "    print(\"\\n\")\n",
    "    time.sleep(5)\n",
    "    print(\"\\\"Yeah... okay. I have to admit this story isn't very original.\\\"\")\n",
    "    time.sleep(3)\n",
    "    print(\"\\\"I'll just do some Indiana Jones type shit...at least that's fun\\\"\")\n",
    "\n",
    "    time.sleep(3)\n",
    "    print(\"\\nYou are an adventurer and fight your way trough a forest. Eventually after days of searching you find something. An entrance to a cave. The dark, long tunnel just asks to be discovered.\\nWhat will you do?\")\n",
    "\n",
    "    time.sleep(5)\n",
    "    choice = input(\"Do you dare to enter the cave (1) or will you just turn around and leave (2)?\")\n",
    "\n",
    "    if choice == \"1\":\n",
    "        time.sleep(3)\n",
    "        print(\"\\nYou take the first step towards the cave entrance and light a torch to see what's in front of you. Your curiosity has won and you disappear into the darkness\")\n",
    "        time.sleep(6)\n",
    "        print(\"\"\"               _______\n",
    "            .-'       '-.\n",
    "          .'             '.\n",
    "         /   _________     \\\\\n",
    "        /   /         \\\\     \\\\\n",
    "       |   |           |     |\n",
    "       |   |           |     |\n",
    "       |   |           |     |\n",
    "        \\\\  \\\\_________/    /\n",
    "         \\\\             _.-'\n",
    "          '._       _.-'\n",
    "             '-._.-'\n",
    "\n",
    "      (•_•)\n",
    "     <)   )╯\n",
    "     /   \\\\\n",
    "\"\"\")\n",
    "\n",
    "    elif choice == \"2\":\n",
    "        time.sleep(3)\n",
    "        print(\"\\nYou turn around and leave like you haven't spent the last few days searching for this. That's just kind of embarrassing.\")\n",
    "        time.sleep(3)\n",
    "        print(r\"\"\"\n",
    "            \\_____/\n",
    "            ( >_< )\n",
    "           =\\(   )>\n",
    "              \\ |\n",
    "               |\\\\\n",
    "              / \\\\==>\n",
    "\"\"\")\n",
    "        exit()\n",
    "\n",
    "    time.sleep(7)\n",
    "    print(\"A few dozens of meters into the cave you find some ancient signs on the walls! Exactly what you were looking for.\")\n",
    "    time.sleep(4)\n",
    "    print(r\"\"\"\n",
    "              ______\n",
    "             |  o o |              ______\n",
    "            /    -  (\\            |  o o |\n",
    "           / /)   (\\ \\\\          /    -  (\\\n",
    "    ______| | | /) \\\\ \\\\        / /)   (\\ \\\\\n",
    "   |  o o | | || \\ || | |______| | | /) \\\\ \\\\\n",
    "  /    -  (\\\\ \\\\ (/ | | |  o o | | || \\ || | |______\n",
    " / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |  o o |\n",
    "| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\n",
    "| | || \\ || | |_o_o__| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\n",
    " \\\\ \\\\ (/ | | |  o o | | || \\ || | |_o_o__| | | /) \\\\ \\\\\n",
    "  \\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |  o o | | || \\ || | |\n",
    "   \\)  -    / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |\n",
    "    |_o_o__| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\\ \\)   (/ /\n",
    "    |  o o | | || \\ || | |_o_o__| | | /) \\\\ \\\\)  -    /\n",
    "   /    -  (\\\\ \\\\ (/ | | |  o o | | || \\ || | |_o_o__|\n",
    "  / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |  o o |\n",
    " | | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\n",
    " | | || \\ || | |_o_o__| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\n",
    "  \\\\ \\\\ (/ | | |  o o | | || \\ || | |_o_o__| | | /) \\\\ \\\\\n",
    "   \\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |  o o | | || \\ || | |\n",
    "    \\)  -    / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |\n",
    "     |_o_o__| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\\ \\)   (/ /\n",
    "            | | || \\ || | |_o_o__| | | /) \\\\ \\\\)  -    /\n",
    "             \\\\ \\\\ (/ | | |      | | || \\ || | |_o_o__|\n",
    "              \\\\ \\)   (/ /        \\\\ \\\\ (/ | | |\n",
    "               \\)  -    /          \\\\ \\)   (/ /\n",
    "                |_o_o__|            \\)  -    /\n",
    "                                     |_o_o__|\n",
    "\"\"\")\n",
    "    time.sleep(6)\n",
    "    print(\"\\nAfter some riddling, the signs turn out to be a map of the cave leading to the hidden temple!\")\n",
    "    time.sleep(6)\n",
    "    print(\"\\nA few minutes after you're faced with a mysterious hallway\")\n",
    "    time.sleep(4)\n",
    "    print(r\"\"\"\n",
    " _____________________________________________\n",
    "|.'',                                     ,''.|\n",
    "|.'.'',                                 ,''.'.|\n",
    "|.'.'.'',                             ,''.'.'.|\n",
    "|.'.'.'.'',                         ,''.'.'.'.|\n",
    "|.'.'.'.'.|                         |.'.'.'.'.|\n",
    "|.'.'.'.'.|===;                 ;===|.'.'.'.'.|\n",
    "|.'.'.'.'.|:::|',             ,'|:::|.'.'.'.'.|\n",
    "|.'.'.'.'.|---|'.|, _______ ,|.'|---|.'.'.'.'.|\n",
    "|.'.'.'.'.|:::|'.|'|???????|'|.'|:::|.'.'.'.'.|\n",
    "|,',',',',|---|',|'|???????|'|,'|---|,',',',',|\n",
    "|.'.'.'.'.|:::|'.|'|???????|'|.'|:::|.'.'.'.'.|\n",
    "|.'.'.'.'.|---|','   /%%%\\   ','|---|.'.'.'.'.|\n",
    "|.'.'.'.'.|===:'    /%%%%%\\    ':===|.'.'.'.'.|\n",
    "|.'.'.'.'.|%%%%%%%%%%%%%%%%%%%%%%%%%|.'.'.'.'.|\n",
    "|.'.'.'.','       /%%%%%%%%%\\       ','.'.'.'.|\n",
    "|.'.'.','        /%%%%%%%%%%%\\        ','.'.'.|\n",
    "|.'.','         /%%%%%%%%%%%%%\\         ','.'.|\n",
    "|.','          /%%%%%%%%%%%%%%%\\          ','.|\n",
    "|;____________/%%%%%%%%%%%%%%%%%\\____________;|\n",
    "\"\"\")\n",
    "    time.sleep(6)\n",
    "    print(\"But now you have to decide in which direction you want to head.\\nTo the left it seems like there is light shimmering from around the corner.\\nTo the right there is another dark tunnel and a whole lot of cobwebs, with no spiders in them (hopefully)...\")\n",
    "\n",
    "    time.sleep(10)\n",
    "    choice = input(\"So which tunnel do you want to head in? To the left, where the light is shimmering (1) or to the right where the cobwebs are obstructing your way (2)?\")\n",
    "\n",
    "    if choice == \"1\":\n",
    "        print(\"Full with courage you head into the left tunnel!\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nAs the light seems to come closer, you step onto a brick plate...\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nA cold breeze blows into your face and you hear a sound of stone scratching...\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nThe ground underneath you begins to move and a gap forms under your feet!\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nYou fall down the hole and... get impaled by many up facing spears!\")\n",
    "\n",
    "        exit()\n",
    "\n",
    "    elif choice == \"2\":\n",
    "        print(\"Full of courage you head into the right tunnel!\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nYou use the torch to burn down the cobwebs...\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nSuddenly you hear multiple screeching sounds...\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nThe screeching comes from many spiders coming from the holes out of the walls... crawling towards you!\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nYou run right through the many cobwebs, just hoping to flee from the spiders\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nYour foot trips over a stone and you fall... just to realise you have escaped the spiders!\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nLooking up you see a room, the room you were looking for.\")\n",
    "        time.sleep(4)\n",
    "        print(\"\\nThe golden Idol on a table placed in the middle of the room\")\n",
    "        time.sleep(4)\n",
    "        print(\"\"\"\n",
    "\n",
    "\n",
    "\n",
    "                                           @#@@%@@@#@#@@+\n",
    "                                       @@@@  *        @  @@@@\n",
    "                                    @@ *.  .:=*@@@%@%*#*+.  #@@@\n",
    "                                  ==     .-*%* .       :#@@*.   @*\n",
    "                                -@ -:=.@@@@%+              #@*   %@#\n",
    "                               -# .:+@@@@#@=@#*:           -%@@@:  @@\n",
    "                              =@ .-@@        -@*@@%#=%@@@=+*+.=@@@. =\n",
    "                              @ .=@           @%@*@@@@@=#-       @@+ @\n",
    "                             @ .-  +@%:==++%%*@@ ##@@@@@@@@@@@@   @@  @\n",
    "                            :-:#@@.    .:      %@@@@      : -=@@@@ @@ @\n",
    "                            @ =%=   :     :-...  @   .   :  %  . --%@  @\n",
    "                            @ @+  .=  @@@.   =+%=  @ =*+@ .@ @@     @@ @\n",
    "                            @ @%+@ @:    *@@  @@@ @@+ @@@*+@@   @ @ .@ @\n",
    "                           + @=  @:   +@@@  + @ @ @ @    @  @@@  #@@+@ @\n",
    "                           @ * @@% :   @@#@#% # @ @ @-%*@@@@@@    @# @ +@  @\n",
    "                        @@ @ %+  @@  +@ @ * %@@*  @%@@     :       @ @+ @@+%\n",
    "                       .*-  :-     %@@@@=@-  @ @  @ @@ .     @@@@@%*@++ . -%\n",
    "                        *:@ - .+@@@@%:   :  @-.@  @-:@@+#@@-  @@*@@%@== @ @-\n",
    "                        *@# -+@@        @  @@ @@  +@#*@ @@@.@     ..*@*.=-=%\n",
    "                        *@*:=#     +@@@@=.*.*@  @@     @@:@@@@@     @@@= @@\n",
    "                            =*   @@@-    @              @#@+@@@@@    .@% @\n",
    "                          @ +@*-=*   +-# @%@@@ *@@ @#@@   @==  .@=@ @=@@\n",
    "                          + +:  .--::.     + @@@*@ @@@@@@** @@%    :.-@@\n",
    "                           -==+  =:.@ *+-@@@#@ %@#.  .:@@@@   @:++  .-%@\n",
    "                           :%-#  -:@ +%+@      += %@ *@    @@  %**  *#@+\n",
    "                            %:- .@@@=-  @      - @@ @     @  @% *@..*@@\n",
    "                           +*++@   @. -@@   @@@@@@      @#@@@ @@ %= @@\n",
    "                           * *+@   @. +  #@.@@@@@@@@@@@@@   @ =@ @  @+\n",
    "                           * .=@*  @* @ @   @      =    @ @ @*-@  -@@ #\n",
    "                           +  .=@*  -*:.  @      @ @ .:.     +@  :@% =@\n",
    "                           * * :=@*    =%::.==       .+###@@+*  @@* *-#\n",
    "                           - @# .=@@         .%@@@@@@. +-      @@. @  @\n",
    "                          = -@= = . %@      @   --+=         @%-.= @@ @\n",
    "                          % %% :  @ @       :@@@@@@@@@:       :@ . :@ *\n",
    "                          # @  = @: @@@@@@                :@@@*  :  *@#\n",
    "                          %*+ --  :=-*-*@@@@@@@@@@@@@@@@@@@*#@@@-   *@:\n",
    "                           @. --: :--   %@@@@@  -=--:%@@@@+=  .@*::  @\n",
    "                           @ .-+-* #=  @@      -@@@@+     @@   @  :  *@\n",
    "                          #@ .-+:@     +                    + . = -  +@\n",
    "                           @ -++ @.@@@#@@@@@@@@@@@@@@@@@@@@@@@.@@-*. =@\n",
    "                           @=..+@. =: #@@@@@@@%       :@@@  :@ @%=--*@\n",
    "                            @+-% ..@@ @@      @@@@@     #@@=%@= @-:#@\n",
    "                             @% --#@:#@@      #   %      @@:  @:+#@#\n",
    "                              @ ++= +#%  +- @@@@@@@@@ *   @#  @@ @\n",
    "                               -+@ :%@   @ @@-     -@@@   +@@  @@\n",
    "                               #%   @@   @% @ @@@@@@ @ @@  =@   @#\n",
    "                               @@   @@  @# @@ @@%@%@@ @  @ @@#  @@\n",
    "                               @@  *@@  %%@  @   @   @ @ - =@@  #@\n",
    "                               @*: -:  @@ @ @@ @ @ @ @. @%#     +@\n",
    "                                .@@:  @+#@   @  # @  @  @ @  #@@@\n",
    "                                   @@@@@@@@@@@@@@@@@@@@@@@@@@@\n",
    "\n",
    "\n",
    "\n",
    "\"\"\")\n",
    "\n",
    "        time.sleep(7)\n",
    "        print(r\"\"\"\n",
    "__   __                                _\n",
    "\\ \\ / /__  _   _  __      _____  _ __ | |\n",
    " \\ V / _ \\| | | | \\ \\ /\\ / / _ \\| '_ \\| |\n",
    "  | | (_) | |_| |  \\ V  V / (_) | | | |_|\n",
    "  |_|\\___/ \\__,_|   \\_/\\_/ \\___/|_| |_(_)\n",
    "\"\"\")\n",
    "\n",
    "\n",
    "else:\n",
    "    print(\"You must type in a 1 to begin your adventure :)\")\n",
    "    time.sleep(2)\n",
    "    print(\"Start again but this time try to read\")\n",
    "\n"
   ],
   "id": "c87d9dc679f2e9ae",
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      " _____                    _\n",
      "|_   _|__ _ __ ___  _ __ | | ___\n",
      "  | |/ _ \\ '_ ` _ \\| '_ \\| |/ _ \\\n",
      "  | |  __/ | | | | | |_) | |  __/\n",
      "  |_|\\___|_|_|_| |_| .__/|_|\\___|\n",
      "   / \\   __| |_   _|_|_ _ __ | |_ _   _ _ __ ___\n",
      "  / _ \\ / _` \\ \\ / / _ \\ '_ \\| __| | | | '__/ _ \\\n",
      " / ___ \\ (_| |\\ V /  __/ | | | |_| |_| | | |  __/\n",
      "/_/   \\_\\__,_| \\_/ \\___|_| |_|\\__|\\__,_|_|  \\___|\n",
      "\n",
      "\"Welcome to the Minigame!\"\n",
      "\n",
      "\"This is not gonna be some cliche adventure. It'll be unique for sure!\"\n",
      "\n",
      "\"So let me think of something...\"\n",
      "\n",
      "\"Wait a second my god!\"\n",
      "\n",
      "\"You're probably one of these TikTok kiddies. I can tell from you're attention span.\"\n",
      "\n",
      "\"Wait! I almost got it...\"\n",
      "\n",
      "\"Oh haha, yeah I know a great, non cliche start to this adventure!\"\n",
      "\n",
      "\"Here we go!\"\n",
      "\n",
      "\n",
      "\n",
      "You awaken in a dark forest. The trees whisper in the wind.\n",
      "Two paths lie before you...\n",
      "\n",
      "\n",
      "        ||      ||\n",
      "        ||      ||\n",
      "     ___||______||_____\n",
      "    /    1     2      /\n",
      "   /                 /\n",
      "  /                 /\n",
      " /                 /\n",
      "/_________________/\n",
      "\n",
      "\n",
      "You walk down the left path and hear the howling of wolves...\n",
      "\n",
      "\n",
      "\"Yeah... okay. I have to admit this story isn't very original.\"\n",
      "\"I'll just do some Indiana Jones type shit...at least that's fun\"\n",
      "\n",
      "You are an adventurer and fight your way trough a forest. Eventually after days of searching you find something. An entrance to a cave. The dark, long tunnel just asks to be discovered.\n",
      "What will you do?\n",
      "\n",
      "You take the first step towards the cave entrance and light a torch to see what's in front of you. Your curiosity has won and you disappear into the darkness\n",
      "               _______\n",
      "            .-'       '-.\n",
      "          .'             '.\n",
      "         /   _________     \\\n",
      "        /   /         \\     \\\n",
      "       |   |           |     |\n",
      "       |   |           |     |\n",
      "       |   |           |     |\n",
      "        \\  \\_________/    /\n",
      "         \\             _.-'\n",
      "          '._       _.-'\n",
      "             '-._.-'\n",
      "\n",
      "      (•_•)\n",
      "     <)   )╯\n",
      "     /   \\\n",
      "\n",
      "A few dozens of meters into the cave you find some ancient signs on the walls! Exactly what you were looking for.\n",
      "\n",
      "              ______\n",
      "             |  o o |              ______\n",
      "            /    -  (\\            |  o o |\n",
      "           / /)   (\\ \\\\          /    -  (\\\n",
      "    ______| | | /) \\\\ \\\\        / /)   (\\ \\\\\n",
      "   |  o o | | || \\ || | |______| | | /) \\\\ \\\\\n",
      "  /    -  (\\\\ \\\\ (/ | | |  o o | | || \\ || | |______\n",
      " / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |  o o |\n",
      "| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\n",
      "| | || \\ || | |_o_o__| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\n",
      " \\\\ \\\\ (/ | | |  o o | | || \\ || | |_o_o__| | | /) \\\\ \\\\\n",
      "  \\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |  o o | | || \\ || | |\n",
      "   \\)  -    / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |\n",
      "    |_o_o__| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\\ \\)   (/ /\n",
      "    |  o o | | || \\ || | |_o_o__| | | /) \\\\ \\\\)  -    /\n",
      "   /    -  (\\\\ \\\\ (/ | | |  o o | | || \\ || | |_o_o__|\n",
      "  / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |  o o |\n",
      " | | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\n",
      " | | || \\ || | |_o_o__| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\n",
      "  \\\\ \\\\ (/ | | |  o o | | || \\ || | |_o_o__| | | /) \\\\ \\\\\n",
      "   \\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |  o o | | || \\ || | |\n",
      "    \\)  -    / /)   (\\ \\\\\\ \\)   (/ /    -  (\\\\ \\\\ (/ | | |\n",
      "     |_o_o__| | | /) \\\\ \\\\)  -    / /)   (\\ \\\\\\ \\)   (/ /\n",
      "            | | || \\ || | |_o_o__| | | /) \\\\ \\\\)  -    /\n",
      "             \\\\ \\\\ (/ | | |      | | || \\ || | |_o_o__|\n",
      "              \\\\ \\)   (/ /        \\\\ \\\\ (/ | | |\n",
      "               \\)  -    /          \\\\ \\)   (/ /\n",
      "                |_o_o__|            \\)  -    /\n",
      "                                     |_o_o__|\n",
      "\n",
      "\n",
      "After some riddling, the signs turn out to be a map of the cave leading to the hidden temple!\n",
      "A few minutes after you're faced with a mysterious hallway\n",
      "\n",
      " _____________________________________________\n",
      "|.'',                                     ,''.|\n",
      "|.'.'',                                 ,''.'.|\n",
      "|.'.'.'',                             ,''.'.'.|\n",
      "|.'.'.'.'',                         ,''.'.'.'.|\n",
      "|.'.'.'.'.|                         |.'.'.'.'.|\n",
      "|.'.'.'.'.|===;                 ;===|.'.'.'.'.|\n",
      "|.'.'.'.'.|:::|',             ,'|:::|.'.'.'.'.|\n",
      "|.'.'.'.'.|---|'.|, _______ ,|.'|---|.'.'.'.'.|\n",
      "|.'.'.'.'.|:::|'.|'|???????|'|.'|:::|.'.'.'.'.|\n",
      "|,',',',',|---|',|'|???????|'|,'|---|,',',',',|\n",
      "|.'.'.'.'.|:::|'.|'|???????|'|.'|:::|.'.'.'.'.|\n",
      "|.'.'.'.'.|---|','   /%%%\\   ','|---|.'.'.'.'.|\n",
      "|.'.'.'.'.|===:'    /%%%%%\\    ':===|.'.'.'.'.|\n",
      "|.'.'.'.'.|%%%%%%%%%%%%%%%%%%%%%%%%%|.'.'.'.'.|\n",
      "|.'.'.'.','       /%%%%%%%%%\\       ','.'.'.'.|\n",
      "|.'.'.','        /%%%%%%%%%%%\\        ','.'.'.|\n",
      "|.'.','         /%%%%%%%%%%%%%\\         ','.'.|\n",
      "|.','          /%%%%%%%%%%%%%%%\\          ','.|\n",
      "|;____________/%%%%%%%%%%%%%%%%%\\____________;|\n",
      "\n",
      "But now you have to decide in which direction you want to head.\n",
      " To the left it seems like there is light shimmering from around the corner.\n",
      "To the right there is another dark tunnel and a whole lot of cobwebs, with no spiders in them (hopefully)...\n",
      "Full of courage you head into the right tunnel!\n",
      "\n",
      "You use the torch to burn down the cobwebs...\n",
      "\n",
      "Suddenly you hear multiple screeching sounds...\n",
      "\n",
      "The screeching comes from many spiders coming from the holes out of the walls... crawling towards you!\n",
      "\n",
      "You run right through the many cobwebs, just hoping to flee from the spiders\n",
      "Your foot trips over a stone and you fall... just to realise you have escaped the spiders!\n",
      "Looking up you see a room, the room you were looking for.\n",
      "The golden Idol on a table placed in the middle of the room\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "                                           @#@@%@@@#@#@@+\n",
      "                                       @@@@  *        @  @@@@\n",
      "                                    @@ *.  .:=*@@@%@%*#*+.  #@@@\n",
      "                                  ==     .-*%* .       :#@@*.   @*\n",
      "                                -@ -:=.@@@@%+              #@*   %@#\n",
      "                               -# .:+@@@@#@=@#*:           -%@@@:  @@\n",
      "                              =@ .-@@        -@*@@%#=%@@@=+*+.=@@@. =\n",
      "                              @ .=@           @%@*@@@@@=#-       @@+ @\n",
      "                             @ .-  +@%:==++%%*@@ ##@@@@@@@@@@@@   @@  @\n",
      "                            :-:#@@.    .:      %@@@@      : -=@@@@ @@ @\n",
      "                            @ =%=   :     :-...  @   .   :  %  . --%@  @\n",
      "                            @ @+  .=  @@@.   =+%=  @ =*+@ .@ @@     @@ @\n",
      "                            @ @%+@ @:    *@@  @@@ @@+ @@@*+@@   @ @ .@ @\n",
      "                           + @=  @:   +@@@  + @ @ @ @    @  @@@  #@@+@ @\n",
      "                           @ * @@% :   @@#@#% # @ @ @-%*@@@@@@    @# @ +@  @\n",
      "                        @@ @ %+  @@  +@ @ * %@@*  @%@@     :       @ @+ @@+%\n",
      "                       .*-  :-     %@@@@=@-  @ @  @ @@ .     @@@@@%*@++ . -%\n",
      "                        *:@ - .+@@@@%:   :  @-.@  @-:@@+#@@-  @@*@@%@== @ @-\n",
      "                        *@# -+@@        @  @@ @@  +@#*@ @@@.@     ..*@*.=-=%\n",
      "                        *@*:=#     +@@@@=.*.*@  @@     @@:@@@@@     @@@= @@\n",
      "                            =*   @@@-    @              @#@+@@@@@    .@% @\n",
      "                          @ +@*-=*   +-# @%@@@ *@@ @#@@   @==  .@=@ @=@@\n",
      "                          + +:  .--::.     + @@@*@ @@@@@@** @@%    :.-@@\n",
      "                           -==+  =:.@ *+-@@@#@ %@#.  .:@@@@   @:++  .-%@\n",
      "                           :%-#  -:@ +%+@      += %@ *@    @@  %**  *#@+\n",
      "                            %:- .@@@=-  @      - @@ @     @  @% *@..*@@\n",
      "                           +*++@   @. -@@   @@@@@@      @#@@@ @@ %= @@\n",
      "                           * *+@   @. +  #@.@@@@@@@@@@@@@   @ =@ @  @+\n",
      "                           * .=@*  @* @ @   @      =    @ @ @*-@  -@@ #\n",
      "                           +  .=@*  -*:.  @      @ @ .:.     +@  :@% =@\n",
      "                           * * :=@*    =%::.==       .+###@@+*  @@* *-#\n",
      "                           - @# .=@@         .%@@@@@@. +-      @@. @  @\n",
      "                          = -@= = . %@      @   --+=         @%-.= @@ @\n",
      "                          % %% :  @ @       :@@@@@@@@@:       :@ . :@ *\n",
      "                          # @  = @: @@@@@@                :@@@*  :  *@#\n",
      "                          %*+ --  :=-*-*@@@@@@@@@@@@@@@@@@@*#@@@-   *@:\n",
      "                           @. --: :--   %@@@@@  -=--:%@@@@+=  .@*::  @\n",
      "                           @ .-+-* #=  @@      -@@@@+     @@   @  :  *@\n",
      "                          #@ .-+:@     +                    + . = -  +@\n",
      "                           @ -++ @.@@@#@@@@@@@@@@@@@@@@@@@@@@@.@@-*. =@\n",
      "                           @=..+@. =: #@@@@@@@%       :@@@  :@ @%=--*@\n",
      "                            @+-% ..@@ @@      @@@@@     #@@=%@= @-:#@\n",
      "                             @% --#@:#@@      #   %      @@:  @:+#@#\n",
      "                              @ ++= +#%  +- @@@@@@@@@ *   @#  @@ @\n",
      "                               -+@ :%@   @ @@-     -@@@   +@@  @@\n",
      "                               #%   @@   @% @ @@@@@@ @ @@  =@   @#\n",
      "                               @@   @@  @# @@ @@%@%@@ @  @ @@#  @@\n",
      "                               @@  *@@  %%@  @   @   @ @ - =@@  #@\n",
      "                               @*: -:  @@ @ @@ @ @ @ @. @%#     +@\n",
      "                                .@@:  @+#@   @  # @  @  @ @  #@@@\n",
      "                                   @@@@@@@@@@@@@@@@@@@@@@@@@@@\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "__   __                                _\n",
      "\\ \\ / /__  _   _  __      _____  _ __ | |\n",
      " \\ V / _ \\| | | | \\ \\ /\\ / / _ \\| '_ \\| |\n",
      "  | | (_) | |_| |  \\ V  V / (_) | | | |_|\n",
      "  |_|\\___/ \\__,_|   \\_/\\_/ \\___/|_| |_(_)\n",
      "\n"
     ]
    }
   ],
   "execution_count": 4
  }
 ],
 "metadata": {
  "kernelspec": {
   "name": "python3",
   "language": "python",
   "display_name": "Python 3 (ipykernel)"
  }
 },
 "nbformat": 5,
 "nbformat_minor": 9
}
